name: Build PDF

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    REGISTRY: ghcr.io

jobs:

    set-vars:
        runs-on: [ubuntu-latest]
        outputs:
            CI_IMAGE : ${{ steps.common.outputs.CI_IMAGE }}
        steps:
            - name: Export common variables.
              id  : common
              run : |
                  echo "CI_IMAGE=${{ env.REGISTRY }}/${{ github.repository }}/latex" >> $GITHUB_OUTPUT

    build-image:
        needs: [set-vars]
        runs-on: [ubuntu-latest]
        container:
            image: docker:latest
        permissions:
            packages: write
        steps:
            - uses: actions/checkout@v4

            - uses: docker/setup-buildx-action@v3

            - uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - uses: docker/build-push-action@v5
              with:
                  context: .
                  platforms: linux/amd64
                  push: true
                  file: dockerfile
                  tags: ${{ needs.set-vars.outputs.CI_IMAGE }}
                  cache-from: type=registry,ref=${{ needs.set-vars.outputs.CI_IMAGE }}
                  cache-to: type=inline
                  labels: "org.opencontainers.image.source=${{ github.repositoryUrl }}"

    build-pdf:
        needs: [set-vars, build-image]
        runs-on: [ubuntu-latest]
        container:
            image: ${{ needs.set-vars.outputs.CI_IMAGE }}
        steps:
            - uses: actions/checkout@v4

            - run: |
                make

            - uses: actions/upload-artifact@v4
              with:
                  path: main.pdf
